### ISSUE TITLE
URGENT: koza hovno

### ISSUE THREAD

**Issue by LufyCZ** [Padi142/krejzac_api#1]

**Comment by Padi142** [comment]
Hi, could you talk a bit more on how do you imagine this feature ?  Iam not sure how to implement it ://

**Comment by LufyCZ** [comment]
Yes

**Comment by LufyCZ** [comment]
bump

**Comment by Padi142** [comment]
@LufyCZ  I still haven't decided how to implement this thing :/ Any ideas ?

**Comment by LufyCZ** [comment]
> @LufyCZ  I still haven't decided how to implement this thing :/ Any ideas ?

IMO it's obvious, no need to explain

**Comment by Padi142** [comment]
screw you @LufyCZ

**Comment by LufyCZ** [comment]
> screw you @LufyCZ 
> 

jsi zmrd grrr
